- name: Install the MariaDB Client and Server
  yum: pkg={{ item }} state=latest
  with_items:
  - "{{ dbserver_pkg }}"
  - "{{ dbclient_pkg }}"
  notify:
    - StartDBService
    - RunSecureInstallPause
    - RestartDbService
    - CopyBkupFile
    - CreateRemoteDB
    - DisplayCreationResults
    - RestoreRemoteDB
    - TestDBResults
    - ShowDBResults
- name: Add a backup CRON Job
  cron: name="DBBackup" minute="0" hour="0" job="mysqldump -u root -ppassword123 -databases MyDBTest > dbbackup.sql"

