--- # DATABASE DEPLOYMENT EXAMPLE
- hosts: mainserver
  user: centoslive
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars: 
    dbserver_pkg: MariaDB-server
    dbclient_pkg: MariaDB-client
    dbserver_fqdn: vinayak.com
    dbinstalldir: /var/lib/
    dbinstancename: MyDBTest
    dbDistribution: RedHat
    dbversion: 5.5
  tasks:
    - name: Install the MariaDB Client and Server
      yum: pkg={{ item }} state=latest
      with_items:
      - "{{ dbserver_pkg }}"
      - "{{ dbclient_pkg }}"
      notify:
       - StartDBService
       - RunSecureInstallPause
       - RestartDbService
       - CopyBkupFile
       - CreateRemoteDB
       - DisplayCreationResults
       - RestoreRemoteDB
       - TestDBResults
       - ShowDBResults
    - name: Add a backup CRON Job
      cron: name="DBBackup" minute="0" hour="0" job="mysqldump -u root -ppassword123 -databases MyDBTest > dbbackup.sql"
  handlers:
    - name: StartDBService
      service: name={{ dbclient_pkg } state=started
    - name: RunSecureInstallPause
      pause: prompt="Please run the mysql_secure_installation binary and then press ENTER for the playbook to continue"
    - name: RestartDbService
      service: name={{ dbclient_pkg }} state=restarted
    - name: CopyBkupFile
      copy: src=files/mysqlbackup.sql dest=/var/lib/mysqlbackup.sql owner=root group=root mode=755
    - name: CreateRemoteDB
      shell: mysqladmin -u root -ppassword123 create { dbinstancename {}
    - name: RestoreRemoteDB
      shell: mysql -u root -ppassword123 {{ dbinstancename }} < {{ dbinstalldir }}/mysqlbackup.sql
      register: result
    - name: DisplayCreationResults
      debug: var=result
    - name: TestDBResults
      shell: mysql -u root -ppassword123 -e 'SHOW DATABASES;'
      register: mysqlresult
    - name: ShowDBResults
      debug: var=mysqlresult
       

